name: Integration Tests

# zizmor ignore note: All caching for pushes to main should be disabled with the `USE_CACHE` env var
on: # zizmor: ignore[cache-poisoning]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ALLOW_PLOTTING: true
  SHELLOPTS: "errexit:pipefail"
  USE_CACHE: ${{
    (
    (github.event_name == 'workflow_dispatch' && github.event.inputs.cache == 'true') ||
    (github.event_name == 'pull_request') ||
    (github.event_name == 'push')
    ) &&
    !startsWith(github.ref, 'refs/tags/v') &&
    !startsWith(github.ref, 'refs/heads/release/') &&
    !startsWith(github.ref, 'refs/heads/main')
    }}

permissions:
  id-token: none

jobs:
  # For now this is just MNE-Python, but others could be added
  mne:
    name: MNE-Python
    runs-on: ubuntu-22.04
    env:
      DISPLAY: ":99.0"
      MNE_LOGGING_LEVEL: "info"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install tox-uv
        run: uv pip install tox-uv

      - name: Run MNE-Python tests
        run: tox r -e integration-mne

      - uses: actions/cache@v4
        if: env.USE_CACHE == 'true'
        with:
          key: ${{ env.TESTING_VERSION }}
          path: ~/mne_data

  pyvistaqt:
    name: PyVistaQt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install tox-uv
        run: uv pip install tox-uv

      - uses: pyvista/setup-headless-display-action@main
        with:
          qt: true
          pyvista: false

      - name: Run pyvistaqt tests
        run: tox r -e integration-pyvistaqt

  geovista:
    name: GeoVista
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        if: env.USE_CACHE == 'true'
        with:
          packages: xvfb
          version: 3.0

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install tox-uv
        run: uv pip install tox-uv

      - name: Run geovista tests
        run: tox r -e integration-geovista

  trame:
    name: Trame
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install tox-uv
        run: uv pip install tox-uv

      - name: Run trame examples
        run: tox r -e integration-trame
