name: Integration Tests

# zizmor ignore note: All caching for pushes to main should be disabled with the `USE_CACHE` env var
on: # zizmor: ignore[cache-poisoning]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ALLOW_PLOTTING: true
  SHELLOPTS: "errexit:pipefail"
  USE_CACHE: ${{
    (
    (github.event_name == 'workflow_dispatch' && github.event.inputs.cache == 'true') ||
    (github.event_name == 'pull_request') ||
    (github.event_name == 'push')
    ) &&
    !startsWith(github.ref, 'refs/tags/v') &&
    !startsWith(github.ref, 'refs/heads/release/') &&
    !startsWith(github.ref, 'refs/heads/main')
    }}

permissions:
  id-token: none

jobs:
  Integration:
    name: ${{matrix.project}}
    strategy:
      fail-fast: false
      matrix:
        project: ["mne", "trame", "pyvistaqt", "geovista"]
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    env:
      DISPLAY: ":99.0"
      MNE_LOGGING_LEVEL: "info"

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: pyvista/setup-headless-display-action@main
        if: ${{matrix.project == 'pyvistaqt'}}
        with:
          qt: true
          pyvista: false

      - uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        if: ${{env.USE_CACHE == 'true' && matrix.project == 'geovista'}}
        with:
          packages: xvfb
          version: 3.0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install tox-uv
        run: uv pip install tox-uv

      - name: Run tests
        run: tox r -e integration-${{matrix.project}}

      - uses: actions/cache@v4
        if: ${{ env.USE_CACHE == 'true' && matrix.project == 'mne' }}
        with:
          key: ${{ env.TESTING_VERSION }}
          path: ~/mne_data
