name: LinkCheck - All files 🔗

on:
  schedule:
    - cron: "0 5 * * 0" # Runs at 05:00 on Sunday.
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: none

jobs:
  doc:
    name: Check Links
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv and
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install tox-uv
        run: uv pip install tox-uv

      - uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        with:
          packages: libosmesa6-dev libgl1-mesa-dev python3-tk pandoc git-restore-mtime
          version: 3.0

      - name: LinkCheck
        run: tox r -e docs-linkcheck
