# check spelling, codestyle
name: Style and Docstring Check

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: none

jobs:
  docstringcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install tox-uv
        run: uv pip install tox-uv

      - uses: actions/cache@v4
        with:
          path: ~/.local/share/pyvista/examples
          key: Examples-Data-${{ hashFiles('*') }}
          restore-keys: |
            Examples-Data-

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v4.2

      - name: Test Package Docstrings
        run: tox run -f doctest --colored=yes

  vale:
    name: Vale
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install test dependencies
        run: uv pip install . --group docs

      # this is equivalent to
      # vale --config doc/.vale.ini doc pyvista examples
      - name: "Run Vale"
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '["doc", "pyvista", "examples"]'
          vale_flags: "--config=doc/.vale.ini"
          reporter: github-pr-check
          level: error
          filter_mode: nofilter
          fail_on_error: true
          version: 2.29.5
          reviewdog_url: https://github.com/reviewdog/reviewdog/releases/download/v0.17.5/reviewdog_0.17.5_Linux_x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
