name: Unit Testing and Deployment

# zizmor ignore note: All caching for pushes to main should be disabled with the `USE_CACHE` env var
on: # zizmor: ignore[cache-poisoning]
  pull_request:
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ALLOW_PLOTTING: true
  SHELLOPTS: "errexit:pipefail"
  USE_CACHE: ${{
    (
    (github.event_name == 'workflow_dispatch' && github.event.inputs.cache == 'true') ||
    (github.event_name == 'pull_request') ||
    (github.event_name == 'push')
    ) &&
    !startsWith(github.ref, 'refs/tags/v') &&
    !startsWith(github.ref, 'refs/heads/release/') &&
    !startsWith(github.ref, 'refs/heads/main')
    }}

permissions:
  id-token: none

jobs:
  macOS:
    name: Mac OS Unit Testing - Python ${{ matrix.config.python-version }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-13, python-version: "3.9" }
          - { os: macos-14, python-version: "3.10" }
          - { os: macos-latest, python-version: "3.11" }
          - { os: macos-latest, python-version: "3.12" }
          - { os: macos-latest, python-version: "3.13" }

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.config.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.config.python-version }}
          if: env.USE_CACHE == 'true'
          cache: "pip"

      - name: Install tox-uv
        run: pip install tox-uv

      - name: Run tests
        run: tox run -e py${{ matrix.config.python-version }} --colored=yes

      - name: Upload Generated Images
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug_images-${{ github.job }}-${{ join(matrix.config.* , '-') }}
          path: debug_images

  Linux:
    name: Linux Unit Testing - Python ${{ matrix.python-version }} - VTK ${{ matrix.vtk-version }} - Numpy ${{ matrix.numpy-version }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

      # see discussion at https://github.com/pyvista/pyvista/issues/2867
      matrix:
        include:
          # numeric numpy versions are ~= conditions, e.g. "1.23" means "numpy~=1.23.0"
          - python-version: "3.9"
            vtk-version: "9.0.3" # Requires numpy~=1.23
            numpy-version: "1.23"
          - python-version: "3.9"
            vtk-version: "9.1"
            numpy-version: "1.26" # Test numpy 1.26
          - python-version: "3.10"
            vtk-version: "9.2.2"
            numpy-version: "latest"
          - python-version: "3.11"
            vtk-version: "9.2.6"
            numpy-version: "latest"
          - python-version: "3.12"
            vtk-version: "9.3.1"
            numpy-version: "latest"
          - python-version: "3.13"
            vtk-version: "9.4.2"
            numpy-version: "latest"
          - python-version: "3.13"
            vtk-version: "latest"
            numpy-version: "nightly"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: Install uv and set the python version ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox-uv
        run: uv pip install tox-uv

      - uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        if: always()
        with:
          packages: xvfb
          version: 3.0

      - uses: actions/cache@v4
        with:
          path: ~/.local/share/pyvista/examples
          key: Examples-1-${{ hashFiles('*') }}
          restore-keys: |
            Examples-1-

      - name: Run tests
        run: |
          xvfb-run -a tox run -e py${{matrix.python-version}}-numpy_${{matrix.numpy-version}}-vtk_${{matrix.vtk-version}}-cov --colored=yes

      - name: Upload Generated Images
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug_images-${{ github.job }}-${{ join(matrix.* , '-') }}
          path: debug_images

      - name: Install coverage
        run: uv pip install coverage

      - uses: codecov/codecov-action@v5
        name: "Upload coverage to CodeCov"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Check package
        run: tox run -e package-check --colored=yes

      - name: Upload to PyPi
        if: matrix.python-version == '3.9' && startsWith(github.ref, 'refs/tags/v')
        run: tox run -e package-publish --colored=yes
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_REPOSITORY_URL: "https://upload.pypi.org/legacy/"

  windows:
    name: Windows Unit Testing - Python ${{ matrix.python-version }}
    runs-on: windows-latest
    env:
      CI_WINDOWS: true
      PYVISTA_USERDATA_PATH: ${{ github.workspace }}\.pyvista_examples
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv and set the python version ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up headless display
        uses: pyvista/setup-headless-display-action@v4.1

      - name: Install tox-uv
        run: uv pip install tox-uv

      - name: Create example data path
        run: mkdir ${{ env.PYVISTA_USERDATA_PATH }} # zizmor: ignore[template-injection]

      - name: Cache example data path
        uses: actions/cache@v4
        with:
          path: ${{ env.PYVISTA_USERDATA_PATH }}
          key: Examples-1-${{ hashFiles('*') }}
          restore-keys: |
            Examples-1-

      - name: Run tests
        run: tox run -e py${{ matrix.python-version }} --colored=yes

      - name: Upload Generated Images
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug_images-${{ github.job }}-${{ join(matrix.* , '-') }}
          path: debug_images
